BT-Lab LOG FILE

Modulo Bat

Run on channel : E1 (SN 0600)
User : 
Ecell ctrl range : min = 0.00 V, max = 9.00 V
Safety Limits :
	Ecell min = 2.90 V
	Ecell max = 4.30 V
	for t > 100 ms
Acquisition started on : 05/05/2021 15:36:22
Saved on :
	File : test_loopsnewoutput_01_MB_CE1.mpr
	Directory : C:\Users\Biologic Server\Documents\BT-Lab\Data\
	Host : 134.79.26.58
Device : BCS-815 (SN 0617)
Address : 134.79.26.101
BT-Lab for windows v1.65 (software)
Internet server v1.65 (firmware)
Command interpretor v1.65 (firmware)
Electrode material : 
Initial state : 
Electrolyte : 
Comments : 
Mass of active material : 0.001 mg
 at x = 0.000
Molecular weight of active material (at x = 0) : 0.001 g/mol
Atomic weight of intercalated ion : 0.001 g/mol
Acquisition started at : xo = 0.000
Number of e- transfered per intercalated ion : 1
for DX = 1, DQ = 26.802 mA.h
Battery capacity : 0.000 A.h
Electrode surface area : 0.001 cm²
Characteristic mass : 0.001 g
Text export
   Mode : Advanced
   Time format : Absolute MMDDYYYY
   Variables : mode;ox;error;time/s;Ecell/V;dq/mA.h;I/mA;(Q-Qo)/mA.h;x;control/V;control/mA;control changes;dQ/mA.h;cycle number;DQ/mA.h;Rapp/Ohm;control/°C;T/°C;rotation rate/rpm;Ns changes;freq/Hz;|Ewe|/V;|I|/A;Phase(Z)/deg;|Z|/Ohm;Re(Z)/Ohm;-Im(Z)/Ohm;I Range;Q charg
   Customize location and naming
      Location : C:\Data
      Naming : {CurrentFile}{FileNum:_}{Ext:.}
Cycle Definition : Charge/Discharge alternance
Ns                  0                   1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  15                  16                  17                  18                  19                  20                  21                  22                  23                  24                  25                  26                  27                  28                  29                  30                  31                  32                  33                  34                  35                  36                  37                  38                  39                  40                  
ctrl_type           Rest                CC                  Rest                CC                  CV                  CC                  Loop                CC                  CV                  Rest                CC                  Rest                CC                  CC                  Loop                CC                  CV                  Loop                Loop                CC                  CV                  CC                  Loop                Loop                CC                  CV                  CC                  Loop                Loop                CC                  CV                  CC                  Loop                Loop                CC                  CC                  CV                  Rest                CC                  Rest                Loop                
Apply I/C           I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   
ctrl1_val                               2.500                                   357.200             4.200               357.200             100.000             832.000             4.200                                   2.500                                   1.875               832.000             100.000             832.000             3.000               100.000             100.000             500.000             4.200               500.000             100.000             100.000             500.000             4.200               2.500               100.000             100.000             500.000             4.200               5.000               100.000             100.000             2.500               2.500               4.200                                   2.500                                   100.000             
ctrl1_val_unit                          A                                       mA                  V                   mA                                      mA                  V                                       A                                       A                   mA                                      mA                  V                                                           mA                  V                   mA                                                          mA                  V                   A                                                           mA                  V                   A                                                           A                   A                   V                                       A                                                           
ctrl1_val_vs                            <None>                                  <None>              Ref                 <None>                                  <None>              Ref                                     <None>                                  <None>              <None>                                  <None>              Ref                                                         <None>              Ref                 <None>                                                      <None>              Ref                 <None>                                                      <None>              Ref                 <None>                                                      <None>              <None>              Ref                                     <None>                                                      
ctrl2_val                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
ctrl2_val_unit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ctrl2_val_vs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
ctrl3_val                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
ctrl3_val_unit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ctrl3_val_vs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
N                   1.00                15.00               1.00                15.00               15.00               15.00               0.00                15.00               15.00               1.00                15.00               1.00                15.00               15.00               0.00                15.00               15.00               0.00                0.00                15.00               15.00               15.00               0.00                0.00                15.00               15.00               15.00               0.00                0.00                15.00               15.00               15.00               0.00                0.00                15.00               15.00               15.00               1.00                15.00               1.00                0.00                
charge/discharge    Charge              Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Discharge           Charge              Discharge           Discharge           Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Charge              Charge              Discharge           Charge              Charge              Charge              Charge              Charge              Charge              Discharge           Charge              Charge              
ctrl_seq            0                   0                   0                   0                   0                   0                   3                   0                   0                   0                   0                   0                   0                   0                   9                   0                   0                   0                   17                  0                   0                   0                   0                   22                  0                   0                   0                   0                   27                  0                   0                   0                   0                   32                  0                   0                   0                   0                   0                   0                   34                  
ctrl_repeat         0                   0                   0                   0                   0                   0                   1                   0                   0                   0                   0                   0                   0                   0                   19                  0                   0                   0                   1                   0                   0                   0                   0                   1                   0                   0                   0                   0                   1                   0                   0                   0                   0                   1                   0                   0                   0                   0                   0                   0                   29                  
ctrl_trigger        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        
ctrl_TO_t           0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
ctrl_TO_t_unit      d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   
ctrl_Nd             6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   
ctrl_Na             1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   
ctrl_corr           1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   
lim_nb              1                   1                   1                   1                   1                   1                   0                   1                   1                   1                   2                   1                   2                   2                   0                   1                   1                   0                   0                   1                   1                   1                   0                   0                   1                   1                   1                   0                   0                   1                   1                   1                   0                   0                   2                   1                   1                   1                   1                   1                   0                   
lim1_type           Time                Time                Time                Ecell               |I|                 Ecell               Time                Ecell               |I|                 Time                Time                Time                Time                Time                Time                Ecell               |I|                 Time                Time                Ecell               |I|                 Ecell               Time                Time                Ecell               |I|                 Ecell               Time                Time                Ecell               |I|                 Ecell               Time                Time                Time                Ecell               Time                Time                Ecell               Time                Time                
lim1_comp           >                   >                   >                   >                   <                   <                   <                   >                   <                   >                   >                   >                   >                   >                   <                   <                   <                   <                   <                   >                   <                   <                   <                   <                   >                   <                   <                   <                   <                   >                   <                   <                   <                   <                   >                   >                   >                   >                   <                   >                   <                   
lim1_Q              Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             
lim1_value          3.000               1.000               1.000               4.200               71.500              3.000               0.000               4.200               125.000             1.000               30.000              40.000              10.000              18.000              0.000               3.000               125.000             0.000               0.000               4.200               125.000             3.000               0.000               0.000               4.200               125.000             3.000               0.000               0.000               4.200               125.000             3.000               0.000               0.000               18.000              4.200               30.000              5.000               3.000               15.000              0.000               
lim1_value_unit     h                   s                   mn                  V                   mA                  V                   s                   V                   mA                  h                   s                   s                   s                   mn                  s                   V                   mA                  s                   s                   V                   mA                  V                   s                   s                   V                   mA                  V                   s                   s                   V                   mA                  V                   s                   s                   mn                  V                   mn                  mn                  V                   mn                  s                   
lim1_action         Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       
lim1_seq            1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  15                  16                  17                  18                  19                  20                  21                  22                  23                  24                  25                  26                  27                  28                  29                  30                  31                  32                  33                  34                  35                  36                  37                  38                  39                  40                  41                  
lim2_type           Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Ecell               Time                Ecell               Ecell               Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Ecell               Time                Time                Time                Time                Time                Time                
lim2_comp           <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   >                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   >                   <                   <                   <                   <                   <                   <                   
lim2_Q              Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             
lim2_value          0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               3.000               0.000               4.290               3.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               4.200               0.000               0.000               0.000               0.000               0.000               0.000               
lim2_value_unit     s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   V                   s                   V                   V                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   V                   s                   s                   s                   s                   s                   s                   
lim2_action         Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Goto sequence       Next sequence       Next sequence       Goto sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Goto sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       
lim2_seq            1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  15                  12                  13                  15                  15                  16                  17                  18                  19                  20                  21                  22                  23                  24                  25                  26                  27                  28                  29                  30                  31                  32                  33                  34                  36                  36                  37                  38                  39                  40                  41                  
rec_nb              1                   1                   2                   2                   2                   2                   0                   2                   2                   2                   1                   1                   1                   2                   0                   2                   2                   0                   0                   2                   2                   2                   0                   0                   2                   2                   2                   0                   0                   2                   2                   2                   0                   0                   2                   2                   1                   1                   2                   1                   0                   
rec1_type           Time                Time                Time                Ecell               Ecell               Ecell               Time                Ecell               Ecell               Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Ecell               Ecell               Ecell               Time                Time                Ecell               Ecell               Ecell               Time                Time                Ecell               Ecell               Ecell               Time                Time                Ecell               Ecell               Time                Time                Ecell               Time                Time                
rec1_value          30.000              10.000              1.000               1.000               1.000               1.000               10.000              1.000               1.000               1.000               10.000              10.000              10.000              30.000              10.000              30.000              30.000              10.000              10.000              1.000               1.000               1.000               10.000              10.000              1.000               1.000               1.000               10.000              10.000              1.000               1.000               1.000               10.000              10.000              5.000               5.000               30.000              30.000              5.000               30.000              10.000              
rec1_value_unit     s                   ms                  s                   mV                  mV                  mV                  s                   mV                  mV                  s                   ms                  ms                  ms                  s                   s                   s                   s                   s                   s                   mV                  mV                  mV                  s                   s                   mV                  mV                  mV                  s                   s                   mV                  mV                  mV                  s                   s                   mV                  mV                  s                   s                   mV                  s                   s                   
rec2_type           Time                Time                Ecell               Time                Time                Time                Time                Time                Time                Ecell               Time                Time                Time                Ecell               Time                Ecell               Ecell               Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                
rec2_value          10.000              10.000              1.000               2.000               2.000               2.000               10.000              30.000              30.000              0.100               10.000              10.000              10.000              1.000               10.000              1.000               1.000               10.000              10.000              30.000              30.000              30.000              10.000              10.000              30.000              30.000              30.000              10.000              10.000              30.000              30.000              30.000              10.000              10.000              30.000              30.000              10.000              10.000              30.000              10.000              10.000              
rec2_value_unit     s                   s                   mV                  mn                  mn                  mn                  s                   s                   s                   mV                  s                   s                   s                   mV                  s                   mV                  mV                  s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   
E range min (V)     0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
E range max (V)     9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               
I Range             10 A                10 A                10 A                10 A                10 A                10 A                1 mA                10 A                10 A                10 A                10 A                10 A                10 A                10 A                1 mA                10 A                10 A                1 mA                1 mA                10 A                10 A                10 A                1 mA                1 mA                10 A                10 A                10 A                1 mA                1 mA                10 A                10 A                10 A                1 mA                1 mA                10 A                10 A                10 A                10 A                10 A                10 A                1 mA                
I Range min         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range max         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range init        Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
auto rest           0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
Bandwidth           4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   
