BT-LAB SETTING FILE

Number of linked techniques : 1

Filename : C:\Users\User\Documents\BT-Lab\Data\formation_Xiao_081420.mps

Device : BCS-815
Ecell ctrl range : min = 0.00 V, max = 9.00 V
Electrode material : 
Initial state : 
Electrolyte : 
Comments : 
Mass of active material : 0.001 mg
 at x = 0.000
Molecular weight of active material (at x = 0) : 0.001 g/mol
Atomic weight of intercalated ion : 0.001 g/mol
Acquisition started at : xo = 0.000
Number of e- transfered per intercalated ion : 1
for DX = 1, DQ = 26.802 mA.h
Battery capacity : 200.000 mA.h
Electrode surface area : 0.001 cm²
Characteristic mass : 0.001 g
Cycle Definition : Charge/Discharge alternance
Do not turn to OCV between techniques

Technique : 1
Modulo Bat
Ns                  0                   1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  
ctrl_type           Rest                CC                  CV                  Rest                CC                  CV                  Rest                CC                  CC                  CC                  Loop                CC                  CC                  CV                  
Apply I/C           I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   I                   
ctrl1_val                               0.100               3.700                                   0.200               4.000                                   0.200               0.500               0.500               0.500               1.000               1.000               3.500               
ctrl1_val_unit                          A                   V                                       A                   V                                       A                   A                   A                                       A                   A                   V                   
ctrl1_val_vs                            <None>              Ref                                     <None>              Ref                                     <None>              <None>              <None>                                  <None>              <None>              Ref                 
ctrl2_val                                                                                                                                                                                                                                                                                                   
ctrl2_val_unit                                                                                                                                                                                                                                                                                              
ctrl2_val_vs                                                                                                                                                                                                                                                                                                
ctrl3_val                                                                                                                                                                                                                                                                                                   
ctrl3_val_unit                                                                                                                                                                                                                                                                                              
ctrl3_val_vs                                                                                                                                                                                                                                                                                                
N                   1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                1.00                
charge/discharge    Charge              Charge              Charge              Charge              Charge              Charge              Charge              Discharge           Charge              Discharge           Discharge           Charge              Discharge           Discharge           
ctrl_seq            0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   8                   8                   8                   8                   
ctrl_repeat         0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   1                   1                   1                   1                   
ctrl_trigger        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        Falling Edge        
ctrl_TO_t           0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
ctrl_TO_t_unit      d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   d                   
ctrl_Nd             6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   6                   
ctrl_Na             1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   
ctrl_corr           1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   
lim_nb              1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   0                   1                   1                   1                   
lim1_type           Time                Ecell               Time                Time                Ecell               Time                Time                Ecell               Ecell               Ecell               Ecell               Ecell               Ecell               Time                
lim1_comp           >                   >                   >                   >                   >                   >                   >                   <                   >                   <                   <                   >                   <                   >                   
lim1_Q              Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             
lim1_value          1.000               3.700               60.000              30.000              4.000               30.000              30.000              3.000               4.100               3.800               3.800               4.200               3.500               5.000               
lim1_value_unit     h                   V                   mn                  mn                  V                   mn                  mn                  V                   V                   V                   V                   V                   V                   mn                  
lim1_action         Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Stop                
lim1_seq            1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  9999                
lim2_type           Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                
lim2_comp           <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   
lim2_Q              Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             
lim2_value          0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
lim2_value_unit     s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   
lim2_action         Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       
lim2_seq            1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  
lim3_type           Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                
lim3_comp           <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   <                   
lim3_Q              Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             Q limit             
lim3_value          0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
lim3_value_unit     s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   
lim3_action         Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       Next sequence       
lim3_seq            1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  
rec_nb              1                   1                   1                   1                   1                   1                   1                   1                   1                   1                   0                   1                   1                   1                   
rec1_type           Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                
rec1_value          1.000               0.002               0.002               0.002               0.010               0.002               0.002               0.002               0.002               0.002               0.001               0.002               0.002               0.002               
rec1_value_unit     s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   
rec2_type           Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                
rec2_value          0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
rec2_value_unit     s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   
rec3_type           Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                Time                
rec3_value          0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
rec3_value_unit     s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   s                   
E range min (V)     0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
E range max (V)     9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               9.000               
I Range             10 mA               10 A                10 A                100 mA              10 A                10 A                10 mA               10 A                10 A                10 A                10 mA               10 A                10 A                10 A                
I Range min         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range max         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range init        Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
auto rest           0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
Bandwidth           4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   4                   
